# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget TryxPS::tryxps)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target TryxPS::tryxps
add_library(TryxPS::tryxps STATIC IMPORTED)

set_target_properties(TryxPS::tryxps PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS/include;D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS;D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS"
)

# Import target "TryxPS::tryxps" for configuration "Debug"
set_property(TARGET TryxPS::tryxps APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TryxPS::tryxps PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS/Debug/tryxps.lib"
  )

# Import target "TryxPS::tryxps" for configuration "Release"
set_property(TARGET TryxPS::tryxps APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TryxPS::tryxps PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS/Release/tryxps.lib"
  )

# Import target "TryxPS::tryxps" for configuration "MinSizeRel"
set_property(TARGET TryxPS::tryxps APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TryxPS::tryxps PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS/MinSizeRel/tryxps.lib"
  )

# Import target "TryxPS::tryxps" for configuration "RelWithDebInfo"
set_property(TARGET TryxPS::tryxps APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TryxPS::tryxps PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Programming_Workspace/C++_Workspace/CLI_Projects/TryxPS/RelWithDebInfo/tryxps.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
